# Generated by Django 6.0.2 on 2026-03-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certs/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'certification',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contact_message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Neelamohan R', max_length=100)),
                ('title', models.CharField(default='Developer & Data Enthusiast', max_length=200)),
                ('bio', models.TextField(default='')),
                ('email', models.EmailField(default='neelamohan6cs@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 9500205859', max_length=20)),
                ('github', models.URLField(default='https://github.com/Neelamohan6cs')),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/neelamohan-r-cs')),
                ('portfolio', models.URLField(default='https://neelamohan-profile.vercel.app/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'db_table': 'hero',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'internship',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=500)),
                ('github_url', models.URLField(blank=True, default='')),
                ('live_url', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('analytics', 'Data Analytics'), ('ml', 'Machine Learning'), ('tools', 'Tools')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=80)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'skill',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'workshop',
                'ordering': ['order'],
            },
        ),
    ]
