# Generated by Django 6.0.2 on 2026-03-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('certificate', 'Certificate'), ('internship', 'Internship'), ('workshop', 'Workshop'), ('project', 'Project'), ('achievement', 'Achievement')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'gallery_image',
                'ordering': ['category', 'order'],
            },
        ),
    ]
