# Generated by Django 6.0.2 on 2026-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/'),
        ),
    ]
