# Generated by Django 4.2.29 on 2026-03-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education_location_educationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
